package pojo;
// Generated 08/06/2017 15:34:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area  implements java.io.Serializable {


     private int codigo;
     private String descricao;
     private Set funcionarios = new HashSet(0);

    public Area() {
    }

	
    public Area(int codigo) {
        this.codigo = codigo;
    }
    public Area(int codigo, String descricao, Set funcionarios) {
       this.codigo = codigo;
       this.descricao = descricao;
       this.funcionarios = funcionarios;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }




}


