package pojo;
// Generated 08/06/2017 15:34:48 by Hibernate Tools 4.3.1



/**
 * Atividade generated by hbm2java
 */
public class Atividade  implements java.io.Serializable {


     private int codigo;
     private Funcionario funcionario;
     private String descricao;
     private Double prazo;

    public Atividade() {
    }

	
    public Atividade(int codigo) {
        this.codigo = codigo;
    }
    public Atividade(int codigo, Funcionario funcionario, String descricao, Double prazo) {
       this.codigo = codigo;
       this.funcionario = funcionario;
       this.descricao = descricao;
       this.prazo = prazo;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Double getPrazo() {
        return this.prazo;
    }
    
    public void setPrazo(Double prazo) {
        this.prazo = prazo;
    }




}


