package pojo;
// Generated 08/06/2017 15:34:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int codigo;
     private Area area;
     private Cargo cargo;
     private String nome;
     private Double tempoExp;
     private Double tempoProj;
     private Set atividades = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int codigo) {
        this.codigo = codigo;
    }
    public Funcionario(int codigo, Area area, Cargo cargo, String nome, Double tempoExp, Double tempoProj, Set atividades) {
       this.codigo = codigo;
       this.area = area;
       this.cargo = cargo;
       this.nome = nome;
       this.tempoExp = tempoExp;
       this.tempoProj = tempoProj;
       this.atividades = atividades;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Area getArea() {
        return this.area;
    }
    
    public void setArea(Area area) {
        this.area = area;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Double getTempoExp() {
        return this.tempoExp;
    }
    
    public void setTempoExp(Double tempoExp) {
        this.tempoExp = tempoExp;
    }
    public Double getTempoProj() {
        return this.tempoProj;
    }
    
    public void setTempoProj(Double tempoProj) {
        this.tempoProj = tempoProj;
    }
    public Set getAtividades() {
        return this.atividades;
    }
    
    public void setAtividades(Set atividades) {
        this.atividades = atividades;
    }




}


