package hibernate;
// Generated 08/06/2017 11:06:05 by Hibernate Tools 4.3.1



/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private Integer cargo;
     private Double tempoExpe;
     private Double tempoProj;
     private Integer area;

    public Funcionario() {
    }

	
    public Funcionario(int codigo) {
        this.codigo = codigo;
    }
    public Funcionario(int codigo, String nome, Integer cargo, Double tempoExpe, Double tempoProj, Integer area) {
       this.codigo = codigo;
       this.nome = nome;
       this.cargo = cargo;
       this.tempoExpe = tempoExpe;
       this.tempoProj = tempoProj;
       this.area = area;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Integer getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Integer cargo) {
        this.cargo = cargo;
    }
    public Double getTempoExpe() {
        return this.tempoExpe;
    }
    
    public void setTempoExpe(Double tempoExpe) {
        this.tempoExpe = tempoExpe;
    }
    public Double getTempoProj() {
        return this.tempoProj;
    }
    
    public void setTempoProj(Double tempoProj) {
        this.tempoProj = tempoProj;
    }
    public Integer getArea() {
        return this.area;
    }
    
    public void setArea(Integer area) {
        this.area = area;
    }




}


